export default {
	TEQUILA_INFO: 'TEQUILA_INFO',
  USER_HISTORY: 'USER_HISTORY',
  PROVIDER_INFO: 'PROVIDER_INFO',
  API: 'http://localhost:8080/api',
  GET_TEQUIINFO_RESPONSE: 'GET_TEQUIINFO_RESPONSE',
  GET_USER_RESPONSE: 'GET_USER_RESPONSE',
  GET_PROVIDER_RESPONSE: 'GET_PROVIDER_RESPONSE',
  NOT_ACCEPTED: 'NOT_ACCEPTED',
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND"
}