export default {
	TEQUILA_INFO: 'TEQUILA_INFO',
  USER_HISTORY: 'USER_HISTORY',
  PROVIDER_INFO: 'PROVIDER_INFO',
  API: 'http://localhost:8080/api',
  API_USER: 'http://localhost:5001/api',
  API_TEQUILA: 'http://localhost:5002/api',
  API_PROVIDER: 'http://localhost:5003/api',
  API_USERTEQUILA: 'http://localhost:5001/addTequilaToUser/',
  GET_TEQUIINFO_RESPONSE: 'GET_TEQUIINFO_RESPONSE',
  GET_USER_RESPONSE: 'GET_USER_RESPONSE',
  GET_PROVIDER_RESPONSE: 'GET_PROVIDER_RESPONSE',
  NOT_ACCEPTED: 'NOT_ACCEPTED',
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  ADD_TEQUILA_USER: "GET_TEQUILA_USER"
}